### ISSUE TITLE
Do you have telegram contact information? I need to find you to customize docker-compose.

### ISSUE THREAD

**Issue by Kia678** [vcwebnetworks/docker-php8#2]
Do you have telegram contact information? I need to find you to customize docker-compose.

**Comment by Kia678** [comment]
Or WhatsApp contact information is also available

**Comment by vagnercardosoweb** [comment]
Hello @Kia678, what would I need? My WhatsApp contact is on my Profile here on Github.
I'm from Brazil, so click on the link there and go.
